---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: all
  #remote_user: root
  remote_user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
